apiVersion: v1
kind: Service
metadata:
  annotations:
    repo: https://github.com/tolson-vkn/wordsandwhiskey.show
  labels:
    app: rabbitmq
    group: celrab
  name: rabbitmq
  namespace: celrab
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
